# Ce workflow va construire et déployer votre application Vite sur GitHub Pages.
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche le déploiement lorsque vous poussez sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    #  AJOUT DE LA PERMISSION SPÉCIFIQUE AU JETON ICI
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project (Creates 'dist' folder)
        run: npm run build

      - name: Deploy to GitHub Pages
        #  FORCER LE JETON DE DÉPLOIEMENT
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Utilise le jeton avec les permissions Write
          publish_dir: ./dist
          force_orphan: true
          cname: '' # Assurez-vous qu'il n'y ait pas de CNAME qui interfère
